---
name: setup
description: setup
author: h0tw1r3

inputs:
    directory:
        description: "required 1"
        required: true
    platform:
        description: "required 2"
        required: true
    project:
        description: "required 3"
        required: true

outputs:
    cache-hit:
        value: ${{ steps.cache-dependencies.outputs.cache-hit }}
    cache-key:
        value: ${{ steps.cache-key.outputs.md5sum }}

runs:
    using: composite
    steps:
        - name: generate cache key
          id: cache-key
          shell: bash
          working-directory: ${{ inputs.directory }}
          run: |
              bundle exec vanagon inspect ${{ inputs.project }} ${{ inputs.platform }} > inspect.json
              echo "md5sum=$(jq -r '.[] | [.url, (.options | join(","))] | @csv' < inspect.json | md5sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

        - name: restore cache
          id: cache
          uses: actions/cache/restore@v4
          with:
              path: ${{ inputs.directory }}/workdir
              key: vanagon-${{ inputs.project }}-dependencies-${{ steps.cache-key.outputs.md5sum }}
              restore-keys: vanagon-${{ inputs.project }}-dependencies-

        - name: dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          working-directory: ${{ inputs.directory }}
          shell: bash
          run: |
              mkdir -p workdir
              bundle exec vanagon dependencies -w "workdir" "${{ inputs.project }}" "${{ inputs.platform }}"
              rm -rf "workdir/patches" ||:

        - name: save cache
          if: steps.cache.outputs.cache-hit != 'true'
          uses: actions/cache/save@v4
          with:
              path: ${{ inputs.directory }}/workdir
              key: vanagon-${{ inputs.project }}-dependencies-${{ steps.cache-key.outputs.md5sum }}
