name: test

on: [push, pull_request]

env:
    platform: debian-12-amd64
    project: dummy
    repository: ospuppet/test-suite-vanagon
    ref: main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: initialize
              uses: ./init
              id: init
              with:
                  repository: ${{ env.repository }}
                  ref: ${{ env.ref }}

            - name: setup project
              uses: ./setup
              id: setup
              with:
                  directory: ${{ steps.init.outputs.directory }}
                  platform: ${{ env.platform }}
                  project: ${{ env.project }}

            - name: build project
              uses: ./build
              id: build
              with:
                  directory: ${{ steps.init.outputs.directory }}
                  cache-key: ${{ steps.setup.outputs.cache-key }}
                  platform: ${{ env.platform }}
                  project: ${{ env.project }}

            - name: show output
              run: |
                  find ${{ steps.build.outputs.artifact-directory }} -type f -print0 | xargs -0 ls -alh
